// packages/angular/src/nx-calendar.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ElementRef,
  OnInit,
  OnDestroy,
  OnChanges,
  SimpleChanges,
  CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';
import '@nexa-calendar/ui';
import type {
  EventInput,
  ViewType,
  ICalendarEvent,
  EventSourceRawInput,
  ICalendarPlugin,
  BusinessHours,
  DropPayload,
  ResourceInput,
} from '@nexa-calendar/core';
import type { NxTheme } from '@nexa-calendar/ui';

type NxCalendarEl = HTMLElement & Record<string, unknown>;

const PROP_KEYS = [
  'events',
  'resources',
  'eventSources',
  'view',
  'views',
  'locale',
  'theme',
  'businessHours',
  'minTime',
  'maxTime',
  'slotDuration',
  'slotLabelFormat',
  'scrollToTime',
  'dayMaxEvents',
  'fixedWeekCount',
  'weekends',
  'showNonCurrentDates',
  'firstDay',
  'editable',
  'eventStartEditable',
  'eventDurationEditable',
  'plugins',
  'headerToolbar',
  'height',
  'aspectRatio',
] as const;

const WC_EVENTS = [
  'dateClick',
  'eventClick',
  'eventDrop',
  'eventResize',
  'drop',
  'editEvent',
] as const;

@Component({
  selector: 'nx-calendar-wrapper',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<nx-calendar #calEl></nx-calendar>`,
})
export class NxCalendarComponent implements OnInit, OnDestroy, OnChanges {
  @Input() events?: EventInput[];
  @Input() resources?: ResourceInput[];
  @Input() eventSources?: EventSourceRawInput[];
  @Input() view?: ViewType;
  @Input() views?: ViewType[];
  @Input() locale?: string;
  @Input() theme?: NxTheme;
  @Input() businessHours?: BusinessHours | BusinessHours[] | boolean;
  @Input() minTime?: string;
  @Input() maxTime?: string;
  @Input() slotDuration?: number;
  @Input() slotLabelFormat?: string;
  @Input() scrollToTime?: string;
  @Input() dayMaxEvents?: number | boolean;
  @Input() fixedWeekCount?: boolean;
  @Input() weekends?: boolean;
  @Input() showNonCurrentDates?: boolean;
  @Input() firstDay?: number;
  @Input() editable?: boolean;
  @Input() eventStartEditable?: boolean;
  @Input() eventDurationEditable?: boolean;
  @Input() plugins?: ICalendarPlugin[];
  @Input() headerToolbar?: boolean | Record<string, string>;
  @Input() height?: 'auto' | number | string;
  @Input() aspectRatio?: number;

  @Output() dateClick = new EventEmitter<{ date: string; allDay: boolean }>();
  @Output() eventClick = new EventEmitter<{ id: string | number; event: ICalendarEvent }>();
  @Output() eventDrop = new EventEmitter<{
    event: ICalendarEvent;
    oldStart: string;
    newStart: string;
  }>();
  @Output() eventResize = new EventEmitter<{
    event: ICalendarEvent;
    oldEnd?: string;
    newEnd: string;
  }>();
  @Output() drop = new EventEmitter<DropPayload>();
  @Output() editEvent = new EventEmitter<{ id: string | number; event: ICalendarEvent }>();

  private _listeners: Array<[string, EventListener]> = [];

  constructor(private _host: ElementRef<HTMLElement>) {}

  private get _el(): NxCalendarEl | null {
    return this._host.nativeElement.querySelector('nx-calendar') as NxCalendarEl | null;
  }

  async ngOnInit(): Promise<void> {
    await customElements.whenDefined('nx-calendar');
    this._applyAllProps();
    this._attachListeners();
  }

  ngOnDestroy(): void {
    this._detachListeners();
  }

  ngOnChanges(changes: SimpleChanges): void {
    const el = this._el;
    if (!el) return;
    for (const key of PROP_KEYS) {
      if (key in changes && changes[key].currentValue !== undefined) {
        el[key] = changes[key].currentValue;
      }
    }
  }

  private _applyAllProps(): void {
    const el = this._el;
    if (!el) return;
    for (const key of PROP_KEYS) {
      const val = (this as Record<string, unknown>)[key];
      if (val !== undefined) el[key] = val;
    }
  }

  private _attachListeners(): void {
    const el = this._el;
    if (!el) return;
    const emitters: Record<string, EventEmitter<unknown>> = {
      dateClick: this.dateClick as EventEmitter<unknown>,
      eventClick: this.eventClick as EventEmitter<unknown>,
      eventDrop: this.eventDrop as EventEmitter<unknown>,
      eventResize: this.eventResize as EventEmitter<unknown>,
      drop: this.drop as EventEmitter<unknown>,
      editEvent: this.editEvent as EventEmitter<unknown>,
    };
    for (const name of WC_EVENTS) {
      const handler = ((e: CustomEvent) => emitters[name].emit(e.detail)) as EventListener;
      el.addEventListener(name, handler);
      this._listeners.push([name, handler]);
    }
  }

  private _detachListeners(): void {
    const el = this._el;
    if (!el) return;
    for (const [name, handler] of this._listeners) {
      el.removeEventListener(name, handler);
    }
    this._listeners = [];
  }

  /** Imperative API passthrough */
  getElement(): NxCalendarEl | null {
    return this._el;
  }
}

// packages/svelte/src/NxCalendar.svelte
<script lang="ts">
  /**
   * NxCalendar Svelte component wrapper.
   * Imperatively sets props on the `nx-calendar` web component.
   */
  import { onMount, onDestroy, createEventDispatcher } from 'svelte'
  import '@nexa-calendar/ui'
  import type {
    EventInput,
    ViewType,
    ICalendarEvent,
    EventSourceRawInput,
    ICalendarPlugin,
    BusinessHours,
    DropPayload,
    ResourceInput,
  } from '@nexa-calendar/core'
  import type { NxTheme } from '@nexa-calendar/ui'

  // Props
  export let events: EventInput[] | undefined = undefined
  export let resources: ResourceInput[] | undefined = undefined
  export let view: ViewType | undefined = undefined
  export let views: ViewType[] | undefined = undefined
  export let locale: string | undefined = undefined
  export let theme: NxTheme | undefined = undefined
  export let businessHours: BusinessHours | BusinessHours[] | boolean | undefined = undefined
  export let minTime: string | undefined = undefined
  export let maxTime: string | undefined = undefined
  export let slotDuration: number | undefined = undefined
  export let slotLabelFormat: string | undefined = undefined
  export let scrollToTime: string | undefined = undefined
  export let dayMaxEvents: number | boolean | undefined = undefined
  export let fixedWeekCount: boolean | undefined = undefined
  export let weekends: boolean | undefined = undefined
  export let showNonCurrentDates: boolean | undefined = undefined
  export let firstDay: number | undefined = undefined
  export let editable: boolean | undefined = undefined
  export let eventStartEditable: boolean | undefined = undefined
  export let eventDurationEditable: boolean | undefined = undefined
  export let headerToolbar: boolean | Record<string, string> | undefined = undefined

  const dispatch = createEventDispatcher<{
    dateClick: { date: string; allDay: boolean }
    eventClick: { id: string | number; event: ICalendarEvent }
    eventDrop: { event: ICalendarEvent; oldStart: string; newStart: string }
    eventResize: { event: ICalendarEvent; oldEnd?: string; newEnd: string }
    drop: DropPayload
    editEvent: { id: string | number; event: ICalendarEvent }
  }>()

  let el: HTMLElement & Record<string, unknown>

  const EVENT_NAMES = ['dateClick', 'eventClick', 'eventDrop', 'eventResize', 'drop', 'editEvent'] as const
  const listeners: Array<[string, EventListener]> = []

  const PROPS: Array<[string, unknown]> = []

  function applyProps(): void {
    if (!el) return
    const propMap: Record<string, unknown> = {
      events, resources, view, views, locale, theme, businessHours,
      minTime, maxTime, slotDuration, slotLabelFormat, scrollToTime,
      dayMaxEvents, fixedWeekCount, weekends, showNonCurrentDates,
      firstDay, editable, eventStartEditable, eventDurationEditable, headerToolbar,
    }
    for (const [key, val] of Object.entries(propMap)) {
      if (val !== undefined) el[key] = val
    }
  }

  onMount(async () => {
    await customElements.whenDefined('nx-calendar')
    applyProps()
    for (const name of EVENT_NAMES) {
      const handler = ((e: CustomEvent) => dispatch(name, e.detail)) as EventListener
      el.addEventListener(name, handler)
      listeners.push([name, handler])
    }
  })

  onDestroy(() => {
    for (const [name, handler] of listeners) {
      el?.removeEventListener(name, handler)
    }
  })

  // Reactive: re-apply when any prop changes
  $: if (el) applyProps()

  /** Expose the underlying WC element */
  export function getElement(): HTMLElement { return el }
</script>

<nx-calendar bind:this={el}></nx-calendar>
